#!/bin/bash
# Batch 1 of 2
# Commands: 460 (Flutter commands filtered out)
set -e  # Stop on error

echo "🚀 Batch 1/2 - 460 commands (No Flutter)"
date

# Create all directories first
mkdir -p -p ~/projects/flutter_trading_app
mkdir -p -p lib/core/errors
mkdir -p -p lib/core/usecases
mkdir -p -p lib/core/utils
mkdir -p -p lib/features/market/data/models
mkdir -p -p lib/features/market/data/datasources
mkdir -p -p lib/features/market/data/repositories
mkdir -p -p lib/features/market/domain/entities
mkdir -p -p lib/features/market/domain/repositories
mkdir -p -p lib/features/market/domain/usecases
mkdir -p -p lib/features/market/presentation/bloc
mkdir -p -p lib/features/market/presentation/pages
mkdir -p -p lib/features/market/presentation/widgets
mkdir -p -p lib/features/market/domain/entities
mkdir -p -p lib/features/market/domain/usecases
mkdir -p -p lib/features/market/data/datasources
mkdir -p -p lib/features/market/presentation/pages
mkdir -p -p lib/features/market/presentation/pages
mkdir -p -p lib/features/market/domain/indicators
mkdir -p -p lib/features/market/data/indicators
mkdir -p -p lib/features/market/domain/trading
mkdir -p -p lib/features/market/data/trading
mkdir -p -p lib/features/market/domain/backtest
mkdir -p -p lib/features/market/data/backtest
mkdir -p -p lib/features/market/presentation/pages/backtest
mkdir -p -p lib/features/market/presentation/widgets/backtest
mkdir -p -p lib/features/market/presentation/pages/settings
mkdir -p -p lib/features/market/presentation/widgets/settings
mkdir -p -p lib/features/market/data/storage
mkdir -p -p lib/core/errors
mkdir -p -p test/core
mkdir -p -p test/features/market/domain
mkdir -p -p test/features/market/data
mkdir -p -p test/features/market/presentation
mkdir -p -p .github/workflows
mkdir -p -p lib/features/market/presentation/bloc/oanda
mkdir -p -p lib/features/market/presentation/bloc/markets
mkdir -p -p lib/features/market/presentation/bloc/chart
mkdir -p -p lib/features/market/presentation/bloc/trading
mkdir -p -p lib/features/market/presentation/bloc/backtest
mkdir -p -p lib/features/market/presentation/bloc/settings
mkdir -p -p lib/features/market/presentation/bloc/chart
mkdir -p -p lib/features/market/presentation/bloc/trading
mkdir -p -p lib/core/widgets
mkdir -p -p lib/features/market/domain/strategy
mkdir -p -p lib/features/market/domain/usecases
mkdir -p -p .github/workflows
mkdir -p -p lib/features/market/data/datasources
mkdir -p -p lib/features/market/presentation/widgets
mkdir -p -p lib/features/market/presentation/widgets/drawing_tools
mkdir -p -p lib/features/market/presentation/bloc/drawing_tools
mkdir -p -p lib/core/notifications
mkdir -p -p lib/features/market/domain/alerts
mkdir -p -p lib/features/market/presentation/bloc/alerts
mkdir -p -p lib/features/market/presentation/pages/alerts
mkdir -p -p lib/features/market/presentation/bloc/backtest
mkdir -p -p lib/features/market/presentation/pages/backtest
mkdir -p -p lib/features/market/presentation/bloc/settings
mkdir -p -p lib/features/market/presentation/pages/settings
mkdir -p -p lib/features/market/presentation/bloc/...
mkdir -p -p lib/core/isolate
mkdir -p -p lib/features/market/presentation/widgets/custom_chart
mkdir -p -p lib/features/market/domain/trading/orders
mkdir -p -p lib/features/market/presentation/bloc/trading_real
mkdir -p -p lib/features/market/data/models/position
mkdir -p -p lib/features/market/presentation/bloc/positions
mkdir -p -p lib/features/market/presentation/pages/positions
mkdir -p -p lib/features/market/domain/audit
mkdir -p -p lib/features/market/data/repositories/audit
mkdir -p -p lib/features/market/presentation/bloc/audit
mkdir -p -p lib/features/market/presentation/pages/audit
mkdir -p -p lib/features/market/domain/indicators/advanced
mkdir -p -p lib/features/market/domain/alerts/smart
mkdir -p -p lib/features/market/domain/alerts/smart/engine
mkdir -p -p lib/features/market/presentation/bloc/smart_alert
mkdir -p -p lib/features/market/domain/analytics
mkdir -p -p lib/features/market/presentation/bloc/analytics
mkdir -p -p lib/features/market/presentation/pages/analytics
mkdir -p -p lib/features/settings/domain/theme
mkdir -p -p lib/features/settings/data/theme
mkdir -p -p lib/features/settings/presentation/bloc/theme
mkdir -p -p lib/features/settings/presentation/pages/theme
mkdir -p -p test/unit
mkdir -p -p test/integration
mkdir -p -p test/widget
mkdir -p -p android/app/src/staging/res/values
mkdir -p -p android/app/src/dev/res/values
mkdir -p -p lib/core/widgets/loading
mkdir -p -p lib/features/market/domain/strategy/multi
mkdir -p -p lib/features/market/presentation/bloc/strategy_comparison
mkdir -p -p lib/features/market/presentation/pages/strategy_comparison
mkdir -p -p lib/features/market/domain/indicators/types
mkdir -p -p lib/features/market/domain/chart
mkdir -p -p lib/features/market/presentation/widgets/custom_chart/utils
mkdir -p -p lib/features/replay/domain/entities
mkdir -p -p lib/features/replay/data/datasources
mkdir -p -p lib/features/replay/domain/engine
mkdir -p -p lib/features/replay/presentation/bloc
mkdir -p -p lib/features/replay/presentation/pages
mkdir -p -p lib/features/strategy_builder/domain/entities
mkdir -p -p lib/features/strategy_builder/domain/models
mkdir -p -p lib/features/strategy_builder/presentation/widgets
mkdir -p -p lib/features/strategy_builder/presentation/pages
mkdir -p -p lib/features/strategy_builder/presentation/canvas
mkdir -p -p lib/features/strategy_builder/domain/interpreter
mkdir -p -p lib/features/strategy_builder/data
mkdir -p -p lib/features/portrait/presentation/pages
mkdir -p -p lib/features/strategy_script/domain
mkdir -p -p lib/features/strategy_script/presentation/pages
mkdir -p -p lib/features/market/presentation/widgets/chart_utils
mkdir -p -p lib/features/market/domain/backtest
mkdir -p -p lib/core/storage/theme
mkdir -p -p lib/core/storage/script
mkdir -p -p lib/core/storage/audit
mkdir -p -p lib/core/storage/indicator
mkdir -p -p lib/core/storage/oanda
mkdir -p -p test/domain/indicators
mkdir -p -p test/domain/backtest
mkdir -p -p test/bloc
mkdir -p -p test/widgets
mkdir -p -p lib/core/models
mkdir -p -p test/models
mkdir -p -p lib/features/strategy/domain/ast
mkdir -p -p lib/features/strategy/domain/indicators
mkdir -p -p lib/features/strategy/domain/evaluator
mkdir -p -p test/strategy
mkdir -p -p lib/core/network
mkdir -p -p lib/features/market/data/streaming
mkdir -p -p lib/features/market/data/rest
mkdir -p -p test/ws
mkdir -p -p lib/features/strategy/domain/indicators
mkdir -p -p test/indicators
mkdir -p -p lib/features/market/domain/backtest
mkdir -p -p test/backtest
mkdir -p -p test/bloc/oanda_setup
mkdir -p -p test/bloc/chart
mkdir -p -p test/bloc/trading
mkdir -p -p test/bloc/backtest
mkdir -p -p lib/core/storage/strategy
mkdir -p -p test/bloc/strategy_builder
mkdir -p -p lib/core/storage/theme
mkdir -p -p test/storage/theme
mkdir -p -p lib/core/storage/script
mkdir -p -p test/storage/script
mkdir -p -p lib/core/storage/audit
mkdir -p -p test/storage/audit
mkdir -p -p lib/core/storage/indicator
mkdir -p -p test/storage/indicator
mkdir -p -p lib/core/storage/replay
mkdir -p -p test/unit/indicators
mkdir -p -p test/unit/backtest
mkdir -p -p test/unit/streaming
mkdir -p -p test/bloc/replay
mkdir -p -p integration_test
mkdir -p -p test/integration/ws
mkdir -p -p lib/core/sync
mkdir -p -p test/sync
mkdir -p -p test/widgets/chart
mkdir -p -p lib/core/network
mkdir -p -p lib/market/data/repositories
mkdir -p -p lib/core/storage/chart_cache
mkdir -p -p test/widgets/offline
mkdir -p -p lib/core/time
mkdir -p -p lib/core/models/price
mkdir -p -p lib/features/strategy/domain/ast
mkdir -p -p lib/features/strategy/domain/signal
mkdir -p -p lib/features/strategy/domain/fsm
mkdir -p -p lib/features/trading/domain
mkdir -p -p lib/features/trading/domain/order
mkdir -p -p lib/features/trading/domain/errors
mkdir -p -p lib/features/trading/domain/history
mkdir -p -p lib/features/trading/domain/audit
mkdir -p -p lib/core/models/dto
mkdir -p -p lib/features/market/domain/repository
mkdir -p -p lib/features/market/data/repository
mkdir -p -p lib/features/trading/domain/interface
mkdir -p -p lib/features/trading/domain/usecases
mkdir -p -p lib/core/async
mkdir -p -p lib/features/market/presentation/bloc/chart
mkdir -p -p lib/features/backtest/domain
mkdir -p -p lib/features/common/data/cache
mkdir -p -p lib/core/network/websocket
mkdir -p -p lib/features/market/data/cache
mkdir -p -p lib/features/market/domain/sync
mkdir -p -p lib/features/indicators/domain
mkdir -p -p lib/features/chart/domain/tools
mkdir -p -p lib/core/storage/hive
mkdir -p -p lib/features/indicators/engine
mkdir -p -p lib/features/indicators/plugins
mkdir -p -p assets/js
mkdir -p -p lib/core/navigation
mkdir -p -p lib/core/widgets
mkdir -p -p lib/features/settings/domain
mkdir -p -p lib/features/settings/presentation
mkdir -p -p lib/features/alerts/domain
mkdir -p -p lib/features/alerts/data
mkdir -p -p lib/features/analytics/domain
mkdir -p -p lib/features/market/presentation/screens
mkdir -p -p lib/features/trading/data/exchanges/crypto
mkdir -p -p lib/features/trading/data/exchanges/stock
mkdir -p -p lib/features/settings/presentation/widgets
mkdir -p -p lib/features/strategy/domain/dsl
mkdir -p -p lib/core/export
mkdir -p -p lib/core/integration/telegram
mkdir -p -p lib/core/export/pdf
mkdir -p -p lib/core/sync/cloud
mkdir -p -p lib/core/export/settings
mkdir -p -p lib/core/permissions
mkdir -p -p lib/features/dashboard/presentation
mkdir -p -p lib/features/replay/domain
mkdir -p -p lib/features/replay/presentation/bloc
mkdir -p -p lib/features/market_depth/domain
mkdir -p -p lib/features/market_depth/presentation/widgets
mkdir -p -p lib/features/market_depth/presentation/bloc
mkdir -p -p lib/features/tape/domain
mkdir -p -p lib/features/tape/presentation/widgets
mkdir -p -p lib/core/network/ws
mkdir -p -p lib/core/streams
mkdir -p -p lib/features/market/data/repository
mkdir -p -p lib/core/compute
mkdir -p -p lib/features/chart/domain
mkdir -p -p lib/features/indicators/domain
mkdir -p -p lib/core/compute
mkdir -p -p lib/features/alerts/data
mkdir -p -p lib/core/storage/sync
mkdir -p -p lib/core/network/ws/parsers
mkdir -p -p lib/features/strategy/domain/dsl
mkdir -p -p lib/features/market/data/cache
mkdir -p -p lib/core/bloc/init
mkdir -p -p lib/core/network/rest
mkdir -p -p lib/features/indicators/data/cache
mkdir -p -p lib/features/strategy/domain
mkdir -p -p lib/core/state/event
mkdir -p -p lib/core/network/ws
mkdir -p -p lib/core/network/retry
mkdir -p -p lib/core/state/shared
mkdir -p -p lib/features/backtest/domain
mkdir -p -p lib/core/state/bloc
mkdir -p -p lib/features/chart/domain
mkdir -p -p lib/features/market/domain
mkdir -p -p lib/features/replay/domain
mkdir -p -p lib/core/widgets/fix
mkdir -p -p lib/features/replay/domain
mkdir -p -p lib/core/lifecycle
mkdir -p -p lib/core/bloc/sync
mkdir -p -p lib/features/trading/domain
mkdir -p -p lib/features/backtest/domain
mkdir -p -p lib/core/lifecycle
mkdir -p -p lib/core/network/ws/lifecycle
mkdir -p -p lib/core/state/tab
mkdir -p -p lib/core/network/ws
mkdir -p -p lib/core/network/rest/parsers
mkdir -p -p lib/core/network/ws/error
mkdir -p -p lib/features/backtest/domain/cancel
mkdir -p -p lib/core/webview
mkdir -p -p lib/features/settings/domain
mkdir -p -p lib/core/network/retry
mkdir -p -p lib/core/storage/transaction
mkdir -p -p lib/core/bloc/subscription_manager
mkdir -p -p lib/core/filters
mkdir -p -p lib/core/queue
mkdir -p -p lib/features/backtest/domain
mkdir -p -p lib/features/trading/data
mkdir -p -p lib/core/sync
mkdir -p -p lib/features/chart/domain/drawing
mkdir -p -p lib/core/buffer
mkdir -p -p lib/core/widgets
mkdir -p -p lib/core/lifecycle
mkdir -p -p lib/features/chart/presentation/bloc
mkdir -p -p lib/features/market/data/repository
mkdir -p -p lib/core/network/ws/smart
mkdir -p -p lib/features/market/presentation/bloc/ws
mkdir -p -p lib/core/data/sanitizer
mkdir -p -p lib/core/network/rest/parsers
mkdir -p -p lib/core/network/ws/parsers
mkdir -p -p lib/features/replay/domain/controller
mkdir -p -p lib/features/replay/presentation/bloc
mkdir -p -p lib/features/backtest/domain/engine
mkdir -p -p lib/features/settings/domain/controllers
mkdir -p -p lib/core/sync
mkdir -p -p lib/features/market/presentation/bloc
mkdir -p -p lib/core/network/error
mkdir -p -p lib/features/market/data/repository
mkdir -p -p lib/core/utils
mkdir -p -p lib/features/market/presentation/bloc
mkdir -p -p lib/core/mode
mkdir -p -p lib/features/backtest/presentation/bloc
mkdir -p -p lib/core/persistence
mkdir -p -p lib/core/lifecycle
mkdir -p -p lib/core/persistence
mkdir -p -p lib/core/time
mkdir -p -p lib/core/bloc/mixins
mkdir -p -p lib/core/state/shared
mkdir -p -p lib/core/network/rest/parsers
mkdir -p -p lib/core/webview
mkdir -p -p lib/features/backtest/domain/strategy
mkdir -p -p lib/features/settings/data
mkdir -p -p lib/core/compute
mkdir -p -p lib/features/alerts/domain
mkdir -p -p lib/core/sync
mkdir -p -p lib/features/strategy/domain
mkdir -p -p lib/core/cache
mkdir -p -p lib/core/chart
mkdir -p -p lib/core/filters
mkdir -p -p lib/features/trading/domain
mkdir -p -p lib/core/network/retry
mkdir -p -p lib/core/bloc/guards
mkdir -p -p lib/core/widgets/fix
mkdir -p -p lib/core/chart/update
mkdir -p -p lib/core/market
mkdir -p -p lib/core/sync
mkdir -p -p lib/features/indicators/domain
mkdir -p -p lib/core/webview/guard
mkdir -p -p lib/core/network/rest/guard
mkdir -p -p lib/core/bloc/mixins
mkdir -p -p lib/features/indicators/domain/gap
mkdir -p -p lib/core/navigation
mkdir -p -p lib/core/compute
mkdir -p -p lib/core/filters
mkdir -p -p lib/core/localization
mkdir -p -p lib/core/utils
mkdir -p -p lib/core/mode
mkdir -p -p lib/core/sync
mkdir -p -p lib/features/backtest/domain/check
mkdir -p -p lib/core/widgets
mkdir -p -p lib/core/network/rest/parsers
mkdir -p -p lib/core/network/ws/backoff
mkdir -p -p lib/core/storage
mkdir -p -p lib/core/widgets
mkdir -p -p lib/core/navigation
mkdir -p -p lib/core/network/rest/timeout
mkdir -p -p lib/core/bloc/mixins
mkdir -p -p lib/core/widgets/mixins
mkdir -p -p lib/core/ui
mkdir -p -p lib/core/time
mkdir -p -p lib/core/chart/data
mkdir -p -p lib/features/market_depth/domain
mkdir -p -p lib/features/trading/domain/execution
mkdir -p -p lib/core/network/ws/security
mkdir -p -p lib/core/security
mkdir -p -p lib/core/network/rest/throttle
mkdir -p -p lib/core/state/paging
mkdir -p -p lib/core/network/ws/manager
mkdir -p -p lib/core/chart/gap
mkdir -p -p lib/core/bloc/mixins
mkdir -p -p lib/features/market/presentation/bloc/chart
mkdir -p -p lib/features/market_depth/presentation/bloc
mkdir -p -p lib/core/cache
mkdir -p -p lib/features/trading/domain/execution
mkdir -p -p lib/core/security
mkdir -p -p lib/features/watchlist/domain
mkdir -p -p lib/core/compute
mkdir -p -p lib/core/network/manager
mkdir -p -p lib/features/chart/data/storage
mkdir -p -p lib/features/indicators/render
mkdir -p -p lib/core/network/rest/guard
mkdir -p -p lib/core/ui/fonts
mkdir -p -p lib/core/state/empty
mkdir -p -p lib/core/notifications
mkdir -p -p lib/core/state/paging
mkdir -p -p lib/core/storage
mkdir -p -p lib/core/state/guard
mkdir -p -p lib/features/trading/domain/execution
mkdir -p -p lib/features/backtest/domain/engine
mkdir -p -p lib/core/network/ws/parsers
mkdir -p -p lib/core/storage
mkdir -p -p lib/core/sync
mkdir -p -p lib/core/network/ws/registry
mkdir -p -p lib/core/startup
mkdir -p -p lib/features/trading/presentation/bloc
mkdir -p -p lib/core/chart/filter
mkdir -p -p lib/core/models/factories
mkdir -p -p lib/features/chart/domain/drawing
mkdir -p -p lib/features/trading/domain/simulation
mkdir -p -p lib/core/network/ws/smart
mkdir -p -p lib/core/bloc/mixins
mkdir -p -p lib/core/models/adapters
mkdir -p -p lib/core/di
mkdir -p -p lib/core/navigation
mkdir -p -p lib/core/bloc
mkdir -p -p lib/core/startup
mkdir -p -p lib/core/ui
mkdir -p -p lib/core/models/adapters
mkdir -p -p lib/features/home/presentation
mkdir -p -p lib/features/home/presentation/pages
mkdir -p -p lib/features/chart/presentation/pages
mkdir -p -p lib/features/settings/presentation/pages
mkdir -p -p lib/features/trading/presentation/pages
mkdir -p -p lib/features/backtest/presentation/pages
mkdir -p -p lib/core/network/oanda
mkdir -p -p lib/core/security
mkdir -p -p lib/core/network/oanda/client
mkdir -p -p lib/core/network/oanda/stream
mkdir -p -p lib/features/market/data
mkdir -p -p lib/features/market/presentation/bloc/oanda
mkdir -p -p lib/features/chart/presentation/bloc
mkdir -p -p lib/features/settings/presentation/pages
mkdir -p -p assets/lightweight_charts
mkdir -p -p lib/features/chart/presentation/widgets
mkdir -p -p lib/features/chart/presentation/bloc/live_chart
mkdir -p -p lib/features/indicators/domain
mkdir -p -p lib/features/indicators/presentation/bloc
mkdir -p -p assets/lightweight_charts
mkdir -p -p lib/features/chart/presentation/widgets
mkdir -p -p lib/features/chart/presentation/bloc/live_chart
mkdir -p -p lib/features/market/domain/aggregator
mkdir -p -p lib/features/market/domain/timeframes
mkdir -p -p lib/features/trading/domain/execution
mkdir -p -p lib/features/trading/data
mkdir -p -p lib/features/trading/presentation/bloc
mkdir -p -p lib/core/security/refresh
mkdir -p -p lib/core/network/security
mkdir -p -p lib/core/network/retry
mkdir -p -p lib/core/logging
mkdir -p -p lib/core/ui/widgets
mkdir -p -p lib/core/ui/styles
mkdir -p -p lib/features/trading/presentation/widgets
mkdir -p -p lib/core/storage
mkdir -p -p lib/core/settings
mkdir -p -p lib/core/logging/ui
mkdir -p -p test/unit
mkdir -p -p test/integration
mkdir -p -p test/widget
mkdir -p -p lib/flavors
mkdir -p -p .github/workflows
mkdir -p -p docs
mkdir -p -p lib/core/network/rest
mkdir -p -p lib/core/network/ws/transport
mkdir -p -p lib/core/network/ws/pipeline
mkdir -p -p lib/features/market/domain/streaming
mkdir -p -p lib/features/market/presentation/bloc/stream
mkdir -p -p lib/features/market/domain/models
mkdir -p -p lib/features/trading/domain/models
mkdir -p -p lib/core/network/security/pinning
mkdir -p -p test/pinning
mkdir -p -p lib/core/network/retry
mkdir -p -p lib/core/storage/hive_adapters
mkdir -p -p lib/core/storage/cache
mkdir -p -p lib/core/bloc
mkdir -p -p lib/core/bloc/subscriptions
mkdir -p -p lib/features/market/presentation/bloc/market
mkdir -p -p lib/core/error
mkdir -p -p lib/features/market/presentation/bloc/market
mkdir -p -p lib/features/market/presentation/bloc/stream
mkdir -p -p lib/core/bloc/root
mkdir -p -p lib/core/bloc/providers
mkdir -p -p lib/core/ui/theme
mkdir -p -p lib/core/ui/widgets
mkdir -p -p lib/core/navigation
mkdir -p -p test/unit/models
mkdir -p -p test/unit/domain
mkdir -p -p test/unit/network
mkdir -p -p test/bloc
mkdir -p -p test/widget
mkdir -p -p integration_test
mkdir -p -p test/network/ws
mkdir -p … 
mkdir -p -p lib/core/ui/widgets
mkdir -p -p lib/core/error
mkdir -p -p scripts

echo '✅ All directories created'


echo "✅ Batch 1 completed (No Flutter commands)"
date
